#!/usr/bin/env python3
"""Fail-closed materializer for the all-radii filter/median:median oracle.

Reads the checked-in, sha256-sidecar-verified
docs/port-engineering/median-parity/median-all-radii-oracles.json (produced
by median_all_radii_oracle_generator.mjs against the immutable authority
snapshot) and writes tests/oracles/median_all_radii_expected.inc: a C++
header the native test (tests/test_median_kernel.cpp) includes directly, so
the native suite never has to shell out to node to get the authority's own
pixel values.

Usage:
  python3 -m tools.glslcpp.generate_median_all_radii_native_oracle_include --check
  python3 -m tools.glslcpp.generate_median_all_radii_native_oracle_include --write
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "docs/port-engineering/median-parity"
ORACLE = PACKAGE / "median-all-radii-oracles.json"
TARGET = ROOT / "tests/oracles/median_all_radii_expected.inc"
SCHEMA = "noisemaker-for-cpp.median.pixel-parity.v2-all-radii"
KEY = "filter/median:median"
WORD = re.compile(r"^0x[0-9a-f]{8}$")
SHA = re.compile(r"^[0-9a-f]{64}$")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _load_oracle() -> dict:
    payload = ORACLE.read_bytes()
    sidecar = (ORACLE.parent / f"{ORACLE.name}.sha256").read_text(encoding="utf-8")
    expected = f"{_sha256(payload)}  {ORACLE.name}\n"
    if sidecar != expected:
        raise SystemExit(f"median-all-radii-oracles.json sidecar drift: {sidecar!r} != {expected!r}")
    document = json.loads(payload)
    if document["schema"] != SCHEMA:
        raise SystemExit(f"unexpected oracle schema {document['schema']!r}")
    if document["programKey"] != KEY:
        raise SystemExit(f"unexpected oracle program key {document['programKey']!r}")
    if not (document["exactFloat32"] and document["exactRgba8"] and document["toleranceNone"]):
        raise SystemExit("oracle does not declare zero-tolerance exact comparison")
    return document


def _cpp_case(case: dict) -> str:
    name = case["name"]
    width = int(case["width"])
    height = int(case["height"])
    controls = case["controls"]
    words = case["outputFloat32Words"]
    bytes_ = case["outputRgba8"]
    if len(words) != width * height * 4 or len(bytes_) != width * height * 4:
        raise SystemExit(f"case {name}: payload length does not match {width}x{height}")
    for word in words:
        if not WORD.fullmatch(word):
            raise SystemExit(f"case {name}: malformed float32 word {word!r}")
    for value in bytes_:
        if not isinstance(value, int) or not 0 <= value <= 255:
            raise SystemExit(f"case {name}: malformed rgba8 byte {value!r}")
    words_text = ",".join(f"{word}u" for word in words)
    bytes_text = ",".join(f"{value}u" for value in bytes_)
    radius = int(controls["radius"])
    threshold = float(controls["threshold"])
    generator = str(case["generator"])
    if not generator:
        raise SystemExit(f"case {name}: missing generator tag")
    return (
        f'Case{{"{name}",{width}u,{height}u,'
        f'"{generator}",{radius},{threshold!r},'
        f"{{{words_text}}},{{{bytes_text}}}}}"
    )


def render(document: dict) -> bytes:
    cases = document["cases"]
    lines = [
        "// Generated by generate_median_all_radii_native_oracle_include.py;"
        " exact checked JSON authority.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "#include <vector>",
        "namespace noisemaker_median_all_radii_oracle {",
        "struct Case {",
        "  std::string_view name;",
        "  std::uint32_t width, height;",
        "  std::string_view generator;",
        "  std::int32_t radius;",
        "  double threshold;",
        "  std::vector<std::uint32_t> output_float32_words;",
        "  std::vector<std::uint8_t> output_rgba8;",
        "};",
        f'inline constexpr std::string_view kSchema="{document["schema"]}";',
        f'inline constexpr std::string_view kProgramKey="{document["programKey"]}";',
        f'inline constexpr std::string_view kSourceRelativePath="{document["sourceRelativePath"]}";',
        f'inline constexpr std::string_view kSourceSha256="{document["sourceSha256"]}";',
        f'inline const std::array<Case,{len(cases)}> kCases = {{',
    ]
    for case in cases:
        lines.append(_cpp_case(case) + ",")
    lines.append("};")
    lines.append("}  // namespace noisemaker_median_all_radii_oracle")
    lines.append("")
    return ("\n".join(lines)).encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    arguments = parser.parse_args(argv)

    document = _load_oracle()
    rendered = render(document)

    if arguments.write:
        TARGET.write_bytes(rendered)
        (TARGET.parent / f"{TARGET.name}.sha256").write_text(
            f"{_sha256(rendered)}  {TARGET.name}\n", encoding="utf-8")
        sys.stdout.write(f"wrote {TARGET}\n")
        return 0

    if not TARGET.exists():
        raise SystemExit(f"{TARGET} does not exist; run --write first")
    current = TARGET.read_bytes()
    sidecar = (TARGET.parent / f"{TARGET.name}.sha256").read_text(encoding="utf-8")
    if sidecar != f"{_sha256(current)}  {TARGET.name}\n":
        raise SystemExit(f"{TARGET}.sha256 drift")
    if current != rendered:
        raise SystemExit(f"{TARGET} is stale relative to {ORACLE}; run --write")
    sys.stdout.write("median all-radii native oracle include matches the checked-in JSON\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
