#!/usr/bin/env python3
"""Fail-closed materializer for the source-bound filter/snow:snow oracle.

Reads the checked-in, sha256-sidecar-verified
docs/port-engineering/snow-parity/snow-oracles.json (produced by
snow_oracle_generator.mjs against the immutable authority snapshot) and
writes tests/oracles/snow_expected.inc: a C++ header the native test
(tests/test_snow_kernel.cpp) includes directly, so the native suite never
has to shell out to node to get the authority's own pixel values.

Usage:
  python3 -m tools.glslcpp.generate_snow_native_oracle_include --check
  python3 -m tools.glslcpp.generate_snow_native_oracle_include --write
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "docs/port-engineering/snow-parity"
ORACLE = PACKAGE / "snow-oracles.json"
TARGET = ROOT / "tests/oracles/snow_expected.inc"
SCHEMA = "noisemaker-for-cpp.snow.pixel-parity.v1"
KEY = "filter/snow:snow"
WORD = re.compile(r"^0x[0-9a-f]{8}$")
SHA = re.compile(r"^[0-9a-f]{64}$")

# Frozen from the committed authority oracle; the adapter source hash was
# independently verified against noisemaker-for-cpu revision 61aa869.
# A recomputed adjacent sidecar cannot authorize a new baseline.
EXPECTED_ORACLE_SHA256 = 'b7737042b1781dc6905d423feca3e4a67276206e9aa47e2c3150d04dc9275400'
EXPECTED_SOURCE = ('src/effects/adapters/snow.js', 3443, '202e0dbf9b1b8e0e7278c87527d6e2b740eb0a23385115c4805a389caab96366')
EXPECTED_CASE_NAMES = (
    '1x1-alpha-zero',
    '1x1-alpha-one',
    '3x1-time-zero',
    '1x3-pause-true',
    '4x3-pause-boundary-exact',
    '4x3-pause-boundary-just-above',
    '4x3-pause-between-tenth-and-half',
    '5x7-density-zero',
    '5x7-density-negative',
    '5x7-density-hundred',
    '5x7-density-above-range',
    '7x5-alpha-near-zero',
    '7x5-alpha-above-one',
    '7x5-alpha-below-zero',
    '9x2-cosine-just-above-epsilon',
    '2x9-cosine-near-half-turn',
    '2x9-cosine-near-full-turn',
    '17x11-default-like',
    '17x11-large-time',
    '11x17-transposed',
    '13x1-negative-time',
)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _load_oracle() -> dict:
    payload = ORACLE.read_bytes()
    sidecar = (ORACLE.parent / f"{ORACLE.name}.sha256").read_text(encoding="utf-8")
    expected = f"{_sha256(payload)}  {ORACLE.name}\n"
    if sidecar != expected:
        raise SystemExit(f"snow-oracles.json sidecar drift: {sidecar!r} != {expected!r}")
    document = json.loads(payload)
    if document["schema"] != SCHEMA:
        raise SystemExit(f"unexpected oracle schema {document['schema']!r}")
    if document["programKey"] != KEY:
        raise SystemExit(f"unexpected oracle program key {document['programKey']!r}")
    if any(document.get(field) is not True
           for field in ("exactFloat32", "exactRgba8", "toleranceNone")):
        raise SystemExit("oracle does not declare zero-tolerance exact comparison")
    source = tuple(document.get(field) for field in
                   ("sourceRelativePath", "sourceBytes", "sourceSha256"))
    if source != EXPECTED_SOURCE or type(document.get("sourceBytes")) is not int:
        raise SystemExit("oracle source identity drift")
    cases = document.get("cases")
    if (not isinstance(cases, list)
            or any(not isinstance(case, dict) for case in cases)
            or tuple(case.get("name") for case in cases) != EXPECTED_CASE_NAMES):
        raise SystemExit("oracle case census drift")
    if _sha256(payload) != EXPECTED_ORACLE_SHA256:
        raise SystemExit("oracle frozen authority payload drift")
    return document


def _cpp_case(case: dict) -> str:
    name = case["name"]
    width = int(case["width"])
    height = int(case["height"])
    controls = case["controls"]
    words = case["outputFloat32Words"]
    bytes_ = case["outputRgba8"]
    if len(words) != width * height * 4 or len(bytes_) != width * height * 4:
        raise SystemExit(f"case {name}: payload length does not match {width}x{height}")
    for word in words:
        if not WORD.fullmatch(word):
            raise SystemExit(f"case {name}: malformed float32 word {word!r}")
    for value in bytes_:
        if not isinstance(value, int) or not 0 <= value <= 255:
            raise SystemExit(f"case {name}: malformed rgba8 byte {value!r}")
    words_text = ",".join(f"{word}u" for word in words)
    bytes_text = ",".join(f"{value}u" for value in bytes_)
    return (
        f'Case{{"{name}",{width}u,{height}u,'
        f'{float(controls["alpha"])!r},{float(controls["time"])!r},'
        f'{float(controls["pause"])!r},{float(controls["density"])!r},'
        f"{{{words_text}}},{{{bytes_text}}}}}"
    )


def render(document: dict) -> bytes:
    cases = document["cases"]
    lines = [
        "// Generated by generate_snow_native_oracle_include.py; exact checked JSON authority.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "#include <vector>",
        "namespace noisemaker_snow_oracle {",
        "struct Case {",
        "  std::string_view name;",
        "  std::uint32_t width, height;",
        "  double alpha, time, pause, density;",
        "  std::vector<std::uint32_t> output_float32_words;",
        "  std::vector<std::uint8_t> output_rgba8;",
        "};",
        f'inline constexpr std::string_view kSchema="{document["schema"]}";',
        f'inline constexpr std::string_view kProgramKey="{document["programKey"]}";',
        f'inline constexpr std::string_view kSourceRelativePath="{document["sourceRelativePath"]}";',
        f'inline constexpr std::string_view kSourceSha256="{document["sourceSha256"]}";',
        f'inline const std::array<Case,{len(cases)}> kCases = {{',
    ]
    for case in cases:
        lines.append(_cpp_case(case) + ",")
    lines.append("};")
    lines.append("}  // namespace noisemaker_snow_oracle")
    lines.append("")
    return ("\n".join(lines)).encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    arguments = parser.parse_args(argv)

    document = _load_oracle()
    rendered = render(document)

    if arguments.write:
        TARGET.write_bytes(rendered)
        (TARGET.parent / f"{TARGET.name}.sha256").write_text(
            f"{_sha256(rendered)}  {TARGET.name}\n", encoding="utf-8")
        sys.stdout.write(f"wrote {TARGET}\n")
        return 0

    if not TARGET.exists():
        raise SystemExit(f"{TARGET} does not exist; run --write first")
    current = TARGET.read_bytes()
    sidecar = (TARGET.parent / f"{TARGET.name}.sha256").read_text(encoding="utf-8")
    if sidecar != f"{_sha256(current)}  {TARGET.name}\n":
        raise SystemExit(f"{TARGET}.sha256 drift")
    if current != rendered:
        raise SystemExit(f"{TARGET} is stale relative to {ORACLE}; run --write")
    sys.stdout.write("snow native oracle include matches the checked-in JSON\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
