// Generated by docs/port-engineering/palette-override/palette_override_oracle_generator.mjs.
// Do not hand-edit -- regenerate from the authority instead. See
// docs/port-engineering/palette-override/palette-override-oracles.json for
// the full oracle (RGBA8 + Float32 digests, per-case DSL sources and
// options) this file's expectations are drawn from.
#include "test_harness.hpp"

#include "noisemaker/renderer.hpp"

using namespace noisemaker;
using namespace noisemaker::graph;

namespace {

TEST(palette_override_oracle_cellNoise_entry_0) {
  // cellNoise/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 0, palette: 0).write(o0)\nrender(o0)\n", options, "cellNoise/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "7c634d8b4bae67abf9e811a6b4f3835483422f9dd830bd31180549a1bad8c75c");
}

TEST(palette_override_oracle_cellNoise_entry_1) {
  // cellNoise/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 0, palette: 1).write(o0)\nrender(o0)\n", options, "cellNoise/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "7c634d8b4bae67abf9e811a6b4f3835483422f9dd830bd31180549a1bad8c75c");
}

TEST(palette_override_oracle_cellNoise_entry_28) {
  // cellNoise/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 0, palette: 28).write(o0)\nrender(o0)\n", options, "cellNoise/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "7c634d8b4bae67abf9e811a6b4f3835483422f9dd830bd31180549a1bad8c75c");
}

TEST(palette_override_oracle_cellNoise_entry_32) {
  // cellNoise/entry-32: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 0, palette: 32).write(o0)\nrender(o0)\n", options, "cellNoise/entry-32.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "7c634d8b4bae67abf9e811a6b4f3835483422f9dd830bd31180549a1bad8c75c");
}

TEST(palette_override_oracle_cellNoise_entry_55) {
  // cellNoise/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 0, palette: 55).write(o0)\nrender(o0)\n", options, "cellNoise/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "7c634d8b4bae67abf9e811a6b4f3835483422f9dd830bd31180549a1bad8c75c");
}

TEST(palette_override_oracle_cellNoise_palette_colorMode_entry_32) {
  // cellNoise/palette-colorMode-entry-32: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 2, palette: 32).write(o0)\nrender(o0)\n", options, "cellNoise/palette-colorMode-entry-32.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "984de34f9bddf4f553bd03dcf6611b78d3424395b7719ad1d2a069702e709572");
}

TEST(palette_override_oracle_cellNoise_palette_colorMode_entry_55) {
  // cellNoise/palette-colorMode-entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 50, speed: 1, colorMode: 2, palette: 55).write(o0)\nrender(o0)\n", options, "cellNoise/palette-colorMode-entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "c1680211bff2a4649e55685d1eef1ebe290d8670016e4eb3d026b7ba3ba63407");
}

TEST(palette_override_oracle_cellNoise_non_default_other_params) {
  // cellNoise/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2170337908;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).cellNoise(shape: 0, scale: 75, cellScale: 87, smooth: 11, paletteMode: 4, seed: 1, tex: none, texInfluence: 2, texIntensity: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, variation: 80, speed: 3, colorMode: 2, palette: 55).write(o0)\nrender(o0)\n", options, "cellNoise/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "e4475f884745473568257fb18ec92ffd169ebec5299223811e9d786c09914c9c");
}

TEST(palette_override_oracle_colorLab_entry_0) {
  // colorLab/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 2, palette: 0).write(o0)\nrender(o0)\n", options, "colorLab/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "824575c2f6d7b1a96d6cd7827c7c94dd79bd79865a920b8b614b7a4ebcf17737");
}

TEST(palette_override_oracle_colorLab_entry_1) {
  // colorLab/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 2, palette: 1).write(o0)\nrender(o0)\n", options, "colorLab/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "824575c2f6d7b1a96d6cd7827c7c94dd79bd79865a920b8b614b7a4ebcf17737");
}

TEST(palette_override_oracle_colorLab_entry_28) {
  // colorLab/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 2, palette: 28).write(o0)\nrender(o0)\n", options, "colorLab/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "824575c2f6d7b1a96d6cd7827c7c94dd79bd79865a920b8b614b7a4ebcf17737");
}

TEST(palette_override_oracle_colorLab_entry_46) {
  // colorLab/entry-46: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 2, palette: 46).write(o0)\nrender(o0)\n", options, "colorLab/entry-46.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "824575c2f6d7b1a96d6cd7827c7c94dd79bd79865a920b8b614b7a4ebcf17737");
}

TEST(palette_override_oracle_colorLab_entry_55) {
  // colorLab/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 2, palette: 55).write(o0)\nrender(o0)\n", options, "colorLab/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "824575c2f6d7b1a96d6cd7827c7c94dd79bd79865a920b8b614b7a4ebcf17737");
}

TEST(palette_override_oracle_colorLab_palette_colorMode_entry_46) {
  // colorLab/palette-colorMode-entry-46: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 4, palette: 46).write(o0)\nrender(o0)\n", options, "colorLab/palette-colorMode-entry-46.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "0e8ff405a54b7d9231c5ff987a1cb191e86da44490ad7fd06006f13678adae8f");
}

TEST(palette_override_oracle_colorLab_palette_colorMode_entry_55) {
  // colorLab/palette-colorMode-entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 0, brightness: 0, contrast: 50, hueRange: 100, colorMode: 4, palette: 55).write(o0)\nrender(o0)\n", options, "colorLab/palette-colorMode-entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "5eb7757d491ef82b0a90a411f5e410c0df1cd11213c715a3397fd6d99a8c2747");
}

TEST(palette_override_oracle_colorLab_non_default_other_params) {
  // colorLab/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 168746864;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).colorLab(paletteMode: 0, saturation: 0, invert: false, levels: 0, dither: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 40, brightness: 15, contrast: 70, hueRange: 100, colorMode: 4, palette: 55).write(o0)\nrender(o0)\n", options, "colorLab/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "93404985e83ac6ccff4e999e1f94016df16dcbfd1d88fe8ad35a44024ef3a7a1");
}

TEST(palette_override_oracle_fractal_entry_0) {
  // fractal/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 0, offsetX: 70, offsetY: 50, colorMode: 4, palette: 0).write(o0)\nrender(o0)\n", options, "fractal/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "9809e4825d97297f43d92391d0cb3f221a3ab874d53e15a5ef100682d97a1405");
}

TEST(palette_override_oracle_fractal_entry_1) {
  // fractal/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 0, offsetX: 70, offsetY: 50, colorMode: 4, palette: 1).write(o0)\nrender(o0)\n", options, "fractal/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "176b486a0e75dcfc6d39057ca6bd743ff79bee0011a4270faf4c7694c6e5100e");
}

TEST(palette_override_oracle_fractal_entry_12) {
  // fractal/entry-12: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 0, offsetX: 70, offsetY: 50, colorMode: 4, palette: 12).write(o0)\nrender(o0)\n", options, "fractal/entry-12.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "6afb87b0ed5b691df80e35692e4759f0fbee6e48ccd70e14c197ffee91cc0f5d");
}

TEST(palette_override_oracle_fractal_entry_28) {
  // fractal/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 0, offsetX: 70, offsetY: 50, colorMode: 4, palette: 28).write(o0)\nrender(o0)\n", options, "fractal/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "1921d263d8407cea17f56d0b0c250377f73c086aea1057190f6f70a2bb656a78");
}

TEST(palette_override_oracle_fractal_entry_55) {
  // fractal/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 0, offsetX: 70, offsetY: 50, colorMode: 4, palette: 55).write(o0)\nrender(o0)\n", options, "fractal/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "505dc40b226912a331a699144439f09c6c4faceda6c3027d4330fbb518936401");
}

TEST(palette_override_oracle_fractal_non_default_other_params) {
  // fractal/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3956202905;
  const auto result = renderer.render("search classicNoisedeck\nfractal(type: 0, symmetry: 0, zoomAmt: 0, speed: 30, centerX: 0, centerY: 0, mode: 0, iterations: 50, paletteMode: 0, hueRange: 100, levels: 0, bgColor: #000000, bgAlpha: 100, cutoff: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, rotation: 45, offsetX: 20, offsetY: 85, colorMode: 4, palette: 28).write(o0)\nrender(o0)\n", options, "fractal/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "fc3b76ffb53646b02361e347b5bc6badfb79ebdc83141326f4a57d74cb203a0b");
}

TEST(palette_override_oracle_noise_entry_0) {
  // noise/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 179, hueRange: 25, kaleido: 1, colorMode: 6, palette: 0).write(o0)\nrender(o0)\n", options, "noise/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "30a26e6596142279a4bd9ffbae60e53788cdb6e257fd192182d5e13c60af3965");
}

TEST(palette_override_oracle_noise_entry_1) {
  // noise/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 179, hueRange: 25, kaleido: 1, colorMode: 6, palette: 1).write(o0)\nrender(o0)\n", options, "noise/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "30a26e6596142279a4bd9ffbae60e53788cdb6e257fd192182d5e13c60af3965");
}

TEST(palette_override_oracle_noise_entry_2) {
  // noise/entry-2: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 179, hueRange: 25, kaleido: 1, colorMode: 6, palette: 2).write(o0)\nrender(o0)\n", options, "noise/entry-2.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "30a26e6596142279a4bd9ffbae60e53788cdb6e257fd192182d5e13c60af3965");
}

TEST(palette_override_oracle_noise_entry_28) {
  // noise/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 179, hueRange: 25, kaleido: 1, colorMode: 6, palette: 28).write(o0)\nrender(o0)\n", options, "noise/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "30a26e6596142279a4bd9ffbae60e53788cdb6e257fd192182d5e13c60af3965");
}

TEST(palette_override_oracle_noise_entry_55) {
  // noise/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 179, hueRange: 25, kaleido: 1, colorMode: 6, palette: 55).write(o0)\nrender(o0)\n", options, "noise/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "30a26e6596142279a4bd9ffbae60e53788cdb6e257fd192182d5e13c60af3965");
}

TEST(palette_override_oracle_noise_non_default_other_params) {
  // noise/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2396922987;
  const auto result = renderer.render("search classicNoisedeck\nnoise(type: 10, octaves: 2, xScale: 75, yScale: 75, ridges: false, wrap: true, seed: 1, refractMode: 2, refractAmt: 0, loopOffset: 300, loopScale: 75, speed: 25, metric: 0, paletteMode: 3, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, hueRotation: 60, hueRange: 90, kaleido: 3, colorMode: 6, palette: 28).write(o0)\nrender(o0)\n", options, "noise/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "3115c5bed189bf93611e9978a11b9796cdac4cb8c5464945bb98a4f6f1dc2393");
}

TEST(palette_override_oracle_shapeMixer_entry_0) {
  // shapeMixer/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 80, palette: 0).write(o0)\nrender(o0)\n", options, "shapeMixer/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "a1323601bb078a54cf9146bbe61c9ce26d95563e0991e2eea155b04adbbe5126");
}

TEST(palette_override_oracle_shapeMixer_entry_1) {
  // shapeMixer/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 80, palette: 1).write(o0)\nrender(o0)\n", options, "shapeMixer/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "9ca49a82e704f5991eddc9c90372af71de1fb950f8fb970610c326267e6b4ef1");
}

TEST(palette_override_oracle_shapeMixer_entry_28) {
  // shapeMixer/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 80, palette: 28).write(o0)\nrender(o0)\n", options, "shapeMixer/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "c859e7b397648d68baf59f5d44de68a0fc8848d0a8fe63120224eb8a120e7f01");
}

TEST(palette_override_oracle_shapeMixer_entry_41) {
  // shapeMixer/entry-41: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 80, palette: 41).write(o0)\nrender(o0)\n", options, "shapeMixer/entry-41.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "a1323601bb078a54cf9146bbe61c9ce26d95563e0991e2eea155b04adbbe5126");
}

TEST(palette_override_oracle_shapeMixer_entry_55) {
  // shapeMixer/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 80, palette: 55).write(o0)\nrender(o0)\n", options, "shapeMixer/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "5eb7757d491ef82b0a90a411f5e410c0df1cd11213c715a3397fd6d99a8c2747");
}

TEST(palette_override_oracle_shapeMixer_non_default_other_params) {
  // shapeMixer/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 3115229185;
  const auto result = renderer.render("search synth, classicNoisedeck\nsolid(color: #3a7).shapeMixer(tex: none, blendMode: 2, wrap: true, seed: 1, animate: 1, paletteMode: 0, levels: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopOffset: 10, loopScale: 40, palette: 55).write(o0)\nrender(o0)\n", options, "shapeMixer/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "5eb7757d491ef82b0a90a411f5e410c0df1cd11213c715a3397fd6d99a8c2747");
}

TEST(palette_override_oracle_shapes_entry_0) {
  // shapes/entry-0: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 1, speedA: 50, palette: 0).write(o0)\nrender(o0)\n", options, "shapes/entry-0.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "8e745563ee031e3a77885b8d01fa929b4c0f2bdf70c6b3bd74664d480decc868");
}

TEST(palette_override_oracle_shapes_entry_1) {
  // shapes/entry-1: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 1, speedA: 50, palette: 1).write(o0)\nrender(o0)\n", options, "shapes/entry-1.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "36630fccc8aabca9c6e84553adecf2dddfa856b35fc117e6a052ca85952acfcc");
}

TEST(palette_override_oracle_shapes_entry_28) {
  // shapes/entry-28: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 1, speedA: 50, palette: 28).write(o0)\nrender(o0)\n", options, "shapes/entry-28.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "8a75794338f2cb2c407090c016724b696bc5a5b08f46ebb849d6dfc84709d16d");
}

TEST(palette_override_oracle_shapes_entry_46) {
  // shapes/entry-46: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 1, speedA: 50, palette: 46).write(o0)\nrender(o0)\n", options, "shapes/entry-46.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "cc5688ad75b8d1afef279227a4fa1cb4454a830a0a2000bae2c2bc570790c917");
}

TEST(palette_override_oracle_shapes_entry_55) {
  // shapes/entry-55: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 1, speedA: 50, palette: 55).write(o0)\nrender(o0)\n", options, "shapes/entry-55.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "79d35eabf5a88db7a4231903cef11ad34a7ba80184f99bcb485c14ab8021ac48");
}

TEST(palette_override_oracle_shapes_non_default_other_params) {
  // shapes/non-default-other-params: mechanically captured from the JS authority by
  // palette_override_oracle_generator.mjs -- see palette-override-oracles.json.
  Renderer renderer;
  RenderOptions options;
  options.width = 17U;
  options.height = 11U;
  options.time = 0.25;
  options.frame = 0;
  options.seed = 2214277204;
  const auto result = renderer.render("search classicNoisedeck\nshapes(loopBOffset: 30, loopBScale: 1, speedB: 50, seed: 1, wrap: true, paletteMode: 0, cyclePalette: 1, rotatePalette: 0, repeatPalette: 1, loopAOffset: 40, loopAScale: 2, speedA: 80, palette: 28).write(o0)\nrender(o0)\n", options, "shapes/non-default-other-params.dsl");
  const auto bytes = result.to_rgba8();
  REQUIRE(bytes.size() == result.width() * result.height() * 4U);
  REQUIRE(detail::sha256(std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size())) ==
          "241c81f17a56cf58dcd29d8e10b664101da5cc55dde24796004753940b343930");
}
}  // namespace
